// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: js_plugins.sql

package sqlc

import (
	"context"
)

const createJSPlugin = `-- name: CreateJSPlugin :execlastid
INSERT INTO js_plugins (name, version, description, author, homepage, license,
    entry_path, main, min_host_version, permissions, update_url, download_url,
    status, zip_hash, entry_hash, file_mod_time, file_path, public_paths)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateJSPluginParams struct {
	Name           string
	Version        string
	Description    string
	Author         string
	Homepage       string
	License        string
	EntryPath      string
	Main           string
	MinHostVersion string
	Permissions    string
	UpdateUrl      string
	DownloadUrl    string
	Status         string
	ZipHash        string
	EntryHash      string
	FileModTime    string
	FilePath       string
	PublicPaths    string
}

func (q *Queries) CreateJSPlugin(ctx context.Context, arg CreateJSPluginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createJSPlugin,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Author,
		arg.Homepage,
		arg.License,
		arg.EntryPath,
		arg.Main,
		arg.MinHostVersion,
		arg.Permissions,
		arg.UpdateUrl,
		arg.DownloadUrl,
		arg.Status,
		arg.ZipHash,
		arg.EntryHash,
		arg.FileModTime,
		arg.FilePath,
		arg.PublicPaths,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteJSPlugin = `-- name: DeleteJSPlugin :exec
DELETE FROM js_plugins WHERE id = ?
`

func (q *Queries) DeleteJSPlugin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJSPlugin, id)
	return err
}

const getJSPluginByEntryPath = `-- name: GetJSPluginByEntryPath :one
SELECT id, name, version, description, author, homepage, license,
    entry_path, main, min_host_version, permissions, update_url, download_url,
    status, zip_hash, entry_hash, file_mod_time, file_path, created_at, updated_at,
    public_paths
FROM js_plugins WHERE entry_path = ?
`

func (q *Queries) GetJSPluginByEntryPath(ctx context.Context, entryPath string) (JsPlugin, error) {
	row := q.db.QueryRowContext(ctx, getJSPluginByEntryPath, entryPath)
	var i JsPlugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Author,
		&i.Homepage,
		&i.License,
		&i.EntryPath,
		&i.Main,
		&i.MinHostVersion,
		&i.Permissions,
		&i.UpdateUrl,
		&i.DownloadUrl,
		&i.Status,
		&i.ZipHash,
		&i.EntryHash,
		&i.FileModTime,
		&i.FilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPaths,
	)
	return i, err
}

const getJSPluginByID = `-- name: GetJSPluginByID :one
SELECT id, name, version, description, author, homepage, license,
    entry_path, main, min_host_version, permissions, update_url, download_url,
    status, zip_hash, entry_hash, file_mod_time, file_path, created_at, updated_at,
    public_paths
FROM js_plugins WHERE id = ?
`

func (q *Queries) GetJSPluginByID(ctx context.Context, id int64) (JsPlugin, error) {
	row := q.db.QueryRowContext(ctx, getJSPluginByID, id)
	var i JsPlugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Author,
		&i.Homepage,
		&i.License,
		&i.EntryPath,
		&i.Main,
		&i.MinHostVersion,
		&i.Permissions,
		&i.UpdateUrl,
		&i.DownloadUrl,
		&i.Status,
		&i.ZipHash,
		&i.EntryHash,
		&i.FileModTime,
		&i.FilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPaths,
	)
	return i, err
}

const listJSPlugins = `-- name: ListJSPlugins :many
SELECT id, name, version, description, author, homepage, license,
    entry_path, main, min_host_version, permissions, update_url, download_url,
    status, zip_hash, entry_hash, file_mod_time, file_path, created_at, updated_at,
    public_paths
FROM js_plugins ORDER BY id
`

func (q *Queries) ListJSPlugins(ctx context.Context) ([]JsPlugin, error) {
	rows, err := q.db.QueryContext(ctx, listJSPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JsPlugin{}
	for rows.Next() {
		var i JsPlugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Author,
			&i.Homepage,
			&i.License,
			&i.EntryPath,
			&i.Main,
			&i.MinHostVersion,
			&i.Permissions,
			&i.UpdateUrl,
			&i.DownloadUrl,
			&i.Status,
			&i.ZipHash,
			&i.EntryHash,
			&i.FileModTime,
			&i.FilePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJSPlugin = `-- name: UpdateJSPlugin :exec
UPDATE js_plugins SET name = ?, version = ?, description = ?, author = ?,
    homepage = ?, license = ?, entry_path = ?, main = ?, min_host_version = ?,
    permissions = ?, update_url = ?, download_url = ?, status = ?,
    zip_hash = ?, entry_hash = ?, file_mod_time = ?, file_path = ?,
    public_paths = ?
WHERE id = ?
`

type UpdateJSPluginParams struct {
	Name           string
	Version        string
	Description    string
	Author         string
	Homepage       string
	License        string
	EntryPath      string
	Main           string
	MinHostVersion string
	Permissions    string
	UpdateUrl      string
	DownloadUrl    string
	Status         string
	ZipHash        string
	EntryHash      string
	FileModTime    string
	FilePath       string
	PublicPaths    string
	ID             int64
}

func (q *Queries) UpdateJSPlugin(ctx context.Context, arg UpdateJSPluginParams) error {
	_, err := q.db.ExecContext(ctx, updateJSPlugin,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Author,
		arg.Homepage,
		arg.License,
		arg.EntryPath,
		arg.Main,
		arg.MinHostVersion,
		arg.Permissions,
		arg.UpdateUrl,
		arg.DownloadUrl,
		arg.Status,
		arg.ZipHash,
		arg.EntryHash,
		arg.FileModTime,
		arg.FilePath,
		arg.PublicPaths,
		arg.ID,
	)
	return err
}

const updateJSPluginHashes = `-- name: UpdateJSPluginHashes :exec
UPDATE js_plugins SET zip_hash = ?, entry_hash = ?, file_mod_time = ? WHERE id = ?
`

type UpdateJSPluginHashesParams struct {
	ZipHash     string
	EntryHash   string
	FileModTime string
	ID          int64
}

func (q *Queries) UpdateJSPluginHashes(ctx context.Context, arg UpdateJSPluginHashesParams) error {
	_, err := q.db.ExecContext(ctx, updateJSPluginHashes,
		arg.ZipHash,
		arg.EntryHash,
		arg.FileModTime,
		arg.ID,
	)
	return err
}

const updateJSPluginStatus = `-- name: UpdateJSPluginStatus :exec
UPDATE js_plugins SET status = ? WHERE id = ?
`

type UpdateJSPluginStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateJSPluginStatus(ctx context.Context, arg UpdateJSPluginStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJSPluginStatus, arg.Status, arg.ID)
	return err
}
