// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type AuthToken struct {
	ID            int64
	TokenID       string
	TokenType     string
	ClientInfo    string
	ExpiresAt     time.Time
	RevokedAt     sql.NullTime
	RevokedBy     string
	RevokedReason string
	CreatedAt     time.Time
}

type Config struct {
	ID        int64
	Key       string
	Value     string
	UpdatedAt time.Time
}

type JsPlugin struct {
	ID             int64
	Name           string
	Version        string
	Description    string
	Author         string
	Homepage       string
	License        string
	EntryPath      string
	Main           string
	MinHostVersion string
	Permissions    string
	UpdateUrl      string
	DownloadUrl    string
	Status         string
	ZipHash        string
	EntryHash      string
	FileModTime    string
	FilePath       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PublicPaths    string
}

type Playlist struct {
	ID          int64
	Type        string
	Name        string
	Description string
	CoverPath   string
	CoverUrl    string
	Labels      string
	Position    int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlaylistSong struct {
	ID         int64
	PlaylistID int64
	SongID     int64
	Position   int64
	AddedAt    time.Time
}

type Song struct {
	ID                  int64
	Type                string
	Title               string
	Artist              string
	Album               string
	Duration            float64
	FilePath            string
	Url                 string
	CoverPath           string
	CoverUrl            string
	Lyric               string
	LyricSource         string
	FileSize            int64
	Format              string
	BitRate             int64
	SampleRate          int64
	IsLive              int64
	PluginEntryPath     string
	SourceData          string
	DedupKey            string
	AddedAt             time.Time
	UpdatedAt           time.Time
	LyricRemoteUrl      string
	Year                int64
	Genre               string
	Fingerprint         string
	FingerprintDuration float64
	Isrc                string
}
