// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist_songs.sql

package sqlc

import (
	"context"
)

const addSongToPlaylist = `-- name: AddSongToPlaylist :exec
INSERT INTO playlist_songs (playlist_id, song_id, position)
VALUES (?, ?, ?)
`

type AddSongToPlaylistParams struct {
	PlaylistID int64
	SongID     int64
	Position   int64
}

func (q *Queries) AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, addSongToPlaylist, arg.PlaylistID, arg.SongID, arg.Position)
	return err
}

const addSongToPlaylistIgnore = `-- name: AddSongToPlaylistIgnore :execrows
INSERT OR IGNORE INTO playlist_songs (playlist_id, song_id, position)
VALUES (?, ?, ?)
`

type AddSongToPlaylistIgnoreParams struct {
	PlaylistID int64
	SongID     int64
	Position   int64
}

func (q *Queries) AddSongToPlaylistIgnore(ctx context.Context, arg AddSongToPlaylistIgnoreParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addSongToPlaylistIgnore, arg.PlaylistID, arg.SongID, arg.Position)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPlaylistSongs = `-- name: CountPlaylistSongs :one
SELECT COUNT(*) FROM playlist_songs WHERE playlist_id = ?
`

func (q *Queries) CountPlaylistSongs(ctx context.Context, playlistID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistSongs, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findSongPositionInPlaylist = `-- name: FindSongPositionInPlaylist :one
SELECT position FROM playlist_songs WHERE playlist_id = ? AND song_id = ?
`

type FindSongPositionInPlaylistParams struct {
	PlaylistID int64
	SongID     int64
}

func (q *Queries) FindSongPositionInPlaylist(ctx context.Context, arg FindSongPositionInPlaylistParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findSongPositionInPlaylist, arg.PlaylistID, arg.SongID)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const getPlaylistSongs = `-- name: GetPlaylistSongs :many
SELECT s.id, s.type, s.title, s.artist, s.album, s.duration,
    s.file_path, s.url, s.cover_path, s.cover_url, s.lyric,
    s.lyric_source, s.file_size, s.format, s.bit_rate,
    s.sample_rate, s.is_live,
    s.plugin_entry_path, s.source_data, s.dedup_key,
    s.added_at, s.updated_at, s.lyric_remote_url
FROM songs s
INNER JOIN playlist_songs ps ON s.id = ps.song_id
WHERE ps.playlist_id = ?
ORDER BY ps.position ASC
`

func (q *Queries) GetPlaylistSongs(ctx context.Context, playlistID int64) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistSongs, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Duration,
			&i.FilePath,
			&i.Url,
			&i.CoverPath,
			&i.CoverUrl,
			&i.Lyric,
			&i.LyricSource,
			&i.FileSize,
			&i.Format,
			&i.BitRate,
			&i.SampleRate,
			&i.IsLive,
			&i.PluginEntryPath,
			&i.SourceData,
			&i.DedupKey,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.LyricRemoteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistSongsPaginated = `-- name: GetPlaylistSongsPaginated :many
SELECT s.id, s.type, s.title, s.artist, s.album, s.duration,
    s.file_path, s.url, s.cover_path, s.cover_url, s.lyric,
    s.lyric_source, s.file_size, s.format, s.bit_rate,
    s.sample_rate, s.is_live,
    s.plugin_entry_path, s.source_data, s.dedup_key,
    s.added_at, s.updated_at, s.lyric_remote_url
FROM songs s
INNER JOIN playlist_songs ps ON s.id = ps.song_id
WHERE ps.playlist_id = ?
ORDER BY ps.position ASC
LIMIT ? OFFSET ?
`

type GetPlaylistSongsPaginatedParams struct {
	PlaylistID int64
	Limit      int64
	Offset     int64
}

func (q *Queries) GetPlaylistSongsPaginated(ctx context.Context, arg GetPlaylistSongsPaginatedParams) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistSongsPaginated, arg.PlaylistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Duration,
			&i.FilePath,
			&i.Url,
			&i.CoverPath,
			&i.CoverUrl,
			&i.Lyric,
			&i.LyricSource,
			&i.FileSize,
			&i.Format,
			&i.BitRate,
			&i.SampleRate,
			&i.IsLive,
			&i.PluginEntryPath,
			&i.SourceData,
			&i.DedupKey,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.LyricRemoteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsContainingSong = `-- name: ListPlaylistsContainingSong :many
SELECT ps.playlist_id
FROM playlist_songs ps
INNER JOIN playlists p ON p.id = ps.playlist_id
WHERE ps.song_id = ? AND p.type = 'normal'
`

func (q *Queries) ListPlaylistsContainingSong(ctx context.Context, songID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsContainingSong, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var playlist_id int64
		if err := rows.Scan(&playlist_id); err != nil {
			return nil, err
		}
		items = append(items, playlist_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSongFromPlaylist = `-- name: RemoveSongFromPlaylist :execrows
DELETE FROM playlist_songs WHERE playlist_id = ? AND song_id = ?
`

type RemoveSongFromPlaylistParams struct {
	PlaylistID int64
	SongID     int64
}

func (q *Queries) RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeSongFromPlaylist, arg.PlaylistID, arg.SongID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSongPositionInPlaylist = `-- name: UpdateSongPositionInPlaylist :execrows
UPDATE playlist_songs SET position = ? WHERE playlist_id = ? AND song_id = ?
`

type UpdateSongPositionInPlaylistParams struct {
	Position   int64
	PlaylistID int64
	SongID     int64
}

func (q *Queries) UpdateSongPositionInPlaylist(ctx context.Context, arg UpdateSongPositionInPlaylistParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSongPositionInPlaylist, arg.Position, arg.PlaylistID, arg.SongID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
