// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) error
	AddSongToPlaylistIgnore(ctx context.Context, arg AddSongToPlaylistIgnoreParams) (int64, error)
	CleanExpiredTokens(ctx context.Context, expiresAt time.Time) (int64, error)
	CountPlaylistSongs(ctx context.Context, playlistID int64) (int64, error)
	CountPlaylistsByCoverPath(ctx context.Context, coverPath string) (int64, error)
	CountPlaylistsContainingSong(ctx context.Context, songID int64) (int64, error)
	CountSongsByCoverPath(ctx context.Context, coverPath string) (int64, error)
	CreateJSPlugin(ctx context.Context, arg CreateJSPluginParams) (int64, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (int64, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (int64, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (int64, error)
	DeleteConfig(ctx context.Context, key string) (int64, error)
	DeleteJSPlugin(ctx context.Context, id int64) error
	DeletePlaylist(ctx context.Context, id int64) (int64, error)
	DeleteSong(ctx context.Context, id int64) (int64, error)
	FindPlaylistByName(ctx context.Context, name string) (int64, error)
	FindPlaylistByNameExcludeID(ctx context.Context, arg FindPlaylistByNameExcludeIDParams) (int64, error)
	FindSongByDedupKey(ctx context.Context, arg FindSongByDedupKeyParams) (int64, error)
	FindSongPositionInPlaylist(ctx context.Context, arg FindSongPositionInPlaylistParams) (int64, error)
	GetConfig(ctx context.Context, key string) (Config, error)
	GetJSPluginByEntryPath(ctx context.Context, entryPath string) (JsPlugin, error)
	GetJSPluginByID(ctx context.Context, id int64) (JsPlugin, error)
	GetMaxPlaylistPosition(ctx context.Context) (int64, error)
	GetPlaylistByID(ctx context.Context, arg GetPlaylistByIDParams) (GetPlaylistByIDRow, error)
	GetPlaylistSongs(ctx context.Context, playlistID int64) ([]Song, error)
	GetPlaylistSongsPaginated(ctx context.Context, arg GetPlaylistSongsPaginatedParams) ([]Song, error)
	GetSongByID(ctx context.Context, id int64) (Song, error)
	GetSongTimestamps(ctx context.Context, id int64) (GetSongTimestampsRow, error)
	GetTokenByID(ctx context.Context, tokenID string) (GetTokenByIDRow, error)
	InsertAutoCreatedPlaylist(ctx context.Context, arg InsertAutoCreatedPlaylistParams) (int64, error)
	IsTokenRevoked(ctx context.Context, arg IsTokenRevokedParams) (bool, error)
	ListAllPlaylistNames(ctx context.Context) ([]string, error)
	ListJSPlugins(ctx context.Context) ([]JsPlugin, error)
	ListLocalSongPaths(ctx context.Context) ([]ListLocalSongPathsRow, error)
	ListPlaylistsContainingSong(ctx context.Context, songID int64) ([]int64, error)
	RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) (int64, error)
	RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error)
	SetConfig(ctx context.Context, arg SetConfigParams) error
	TouchPlaylist(ctx context.Context, arg TouchPlaylistParams) (int64, error)
	UpdateJSPlugin(ctx context.Context, arg UpdateJSPluginParams) error
	UpdateJSPluginHashes(ctx context.Context, arg UpdateJSPluginHashesParams) error
	UpdateJSPluginStatus(ctx context.Context, arg UpdateJSPluginStatusParams) error
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (int64, error)
	UpdatePlaylistPosition(ctx context.Context, arg UpdatePlaylistPositionParams) (int64, error)
	UpdateRemoteSongMutable(ctx context.Context, arg UpdateRemoteSongMutableParams) error
	UpdateSong(ctx context.Context, arg UpdateSongParams) (int64, error)
	UpdateSongDuration(ctx context.Context, arg UpdateSongDurationParams) error
	UpdateSongLyrics(ctx context.Context, arg UpdateSongLyricsParams) (int64, error)
	UpdateSongPositionInPlaylist(ctx context.Context, arg UpdateSongPositionInPlaylistParams) (int64, error)
	UpdateSongSource(ctx context.Context, arg UpdateSongSourceParams) error
}

var _ Querier = (*Queries)(nil)
